micronaut:
  application:
    name: demo
  server:
    thread-selection: auto
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger/views/rapidoc
          - classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
        generator:
          refresh-token:
            secret: ${JWT_GENERATOR_REFRESH_TOKEN_SECRET:pleaseChangeThisSecretForANewOne}
    endpoints:
      oauth:
        path: /refresh_token
    intercept-url-map:
      - pattern: ${micronaut.router.static-resources.swagger.mapping}
        http-method: GET
        access:
          - isAnonymous()
    redirect:
      forbidden:
        enabled: false
      unauthorized:
        enabled: false
      refresh:
        enabled: false
---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true