micronaut:
  application:
    name: demo
  server:
    thread-selection: auto
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths:
          - classpath:META-INF/swagger/views/rapidoc
          - classpath:META-INF/swagger
        mapping: /swagger/**
---
datasources:
  default:
    url: jdbc:mysql://localhost:3306/db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
flyway:
  datasources:
    default:
      enabled: true